"""Generate the deployable category registry from the ccn-report taxonomy."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = Path(__file__).parent / 'task_service/app/domain/category_data.py'


def generate(source: Path) -> str:
    categories = json.loads((source / 'categories.json').read_text(encoding='utf-8'))
    records = []
    for index, (primary, children) in enumerate(categories.items(), 1):
        if not primary.startswith(f'{index:02d}-'):
            raise ValueError('Category ordering and numbered names disagree')
        text = (source / f'{index:02d}.md').read_text(encoding='utf-8')
        scope = text.split('## 顶层责任\n', 1)[1].split('\n## ', 1)[0].strip()
        rows = {line.split('|')[1].strip(): line.split('|')[2].strip() for line in text.splitlines() if line.startswith('| ')}
        records.append(dict(value=primary, primary=primary, scope=scope))
        records.extend(dict(value=primary+'/'+child, primary=primary, scope=rows[child]) for child in children)
    return '# Generated by sync_categories.py; edit ccn-report/classification instead.\nCATEGORY_DETAILS = '+json.dumps(records, ensure_ascii=False, indent=2)+'\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--source', type=Path, default=ROOT/'ccn-report/classification')
    args = parser.parse_args()
    expected = generate(args.source)
    if args.write:
        OUTPUT.write_text(expected, encoding='utf-8')
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != expected:
        print('Category registry is stale: run loops/ccn-brief-report/sync_categories.py --write')
        return 1
    print('Category registry verified.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
